services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: cloudadmin
      POSTGRES_PASSWORD: cloudpassword
      POSTGRES_DB: cloudplatform

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

